// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
        "aws_project_region": "ap-southeast-1",
        "aws_cognito_identity_pool_id": "ap-southeast-1:bb093e01-a1c6-481c-9bb6-9a5ffa625bf5",
        "aws_cognito_region": "ap-southeast-1",
        "aws_user_pools_id": "ap-southeast-1_f6n7UvlcT",
        "aws_user_pools_web_client_id": "4rp3l5tl7ge24fnlbj7dhpcgdr",
        "oauth": {},
        "aws_cloud_logic_custom": [
            {
                "name": "rest_api",
                "endpoint": "https://48bdvivhha.execute-api.ap-southeast-1.amazonaws.com/v1",
                "region": "ap-southeast-1"
            }
        ]
};


export default awsmobile;
