// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
        "aws_project_region": window.__initialState.awsConfig.Auth.region,
        "aws_cognito_identity_pool_id": window.__initialState.awsConfig.Auth.identityPoolId,
        "aws_cognito_region": window.__initialState.awsConfig.Auth.region,
        "aws_user_pools_id": window.__initialState.awsConfig.Auth.userPoolId,
        "aws_user_pools_web_client_id": window.__initialState.awsConfig.Auth.UserPoolWebClientId,
        "oauth": {},
        "aws_cloud_logic_custom": [
            {
                "name": window.__initialState.awsConfig.API.endpoints[0].name,
                "endpoint": window.__initialState.awsConfig.API.endpoints[0].endpoint,
                "region": window.__initialState.awsConfig.API.endpoints[0].region
            }
        ]
};


export default awsmobile;
